access:  
  subscription_id: your subscription id
  client_id      : your client id
  client_secret  : your client secret
  tenant_id      : your
user: 
  admin_username: adminuser
  admin_password: your password